version: "3"
services:
  codeigniter-3:
    build: .
    ports:
      - "8090:80"
    # networks:
    #   - app-network
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.6
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'payroll'
      MYSQL_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command: ["--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION", "--init-file", "/docker-entrypoint-initdb.d/payroll.sql"]
    volumes:
      - db_data:/var/lib/mysql
      - ./payroll.sql:/docker-entrypoint-initdb.d/payroll.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'root'
    depends_on:
      - db

volumes:
  db_data: